faern/oneshot

CHANGELOG.md, src/lib.rs, tests/future.rs, tests/helpers/mod.rs, tests/sync.rs
Fixes the issue described in https://github.com/faern/oneshot/issues/10#issuecomment-908132265. The `Future` implementation of `Receiver` does not correctly store the last `Waker` it was given, it only stores the first. This PR adds a test showing how it fails when polled multiple times and then fixes the issue.
As far as I'm aware this is not really an issue in practice on `tokio` or `async-std`. But it still breaks the contract of `Future`, so it should of course be fixed to be sound!
=> Fix keep latest waker bug

.github/workflows/build-and-test.yml, Cargo.toml, tests/async.rs
Updates a number of vulnerable dependencies. 
Firstly, `loom` which has the `generator` [vulnerability](https://rustsec.org/advisories/RUSTSEC-2020-0151), this should be fully fixed. It also now has the `chrono` [vulnerability](https://rustsec.org/advisories/RUSTSEC-2020-0159), though `loom` still needs a version bump, a simple `cargo update` will suffice once it's released. The [PR](https://github.com/tokio-rs/loom/issues/237) has been merged so it shouldn't be long now. 
I've also updated `tokio` and `async-std`.
=> Update deps and fix vulnerabilities

src/errors.rs, src/lib.rs
The nomicon has been outdated about this since 2015,
see rust-lang/nomicon#363 for the update. 
We don't need to tell dropck that we are owning a T as it
can already infer that from the generic parameter in the drop impl.
cc @Cassy343 who added it
=> Remove `_dropck` flag from `SendError`

src/lib.rs, tests/sync.rs
I found this crate when looking for a simple oneshot implementation and decided to try to make some improvements. I removed the UB caused by taking multiple mutable references to the channel concurrently, and fixed a couple UAF errors which could crop up due to unlucky thread interleaving (specifically if the sending thread yielded while unparking the receiving thread).
I'm making this a draft pull request since I'm not very satisfied with the implementation of `Future::poll`. I think there are some improvements that could be made there and I have not spent as much mental energy verifying its correctness. I noticed that the receiver itself currently implements `Future`, but I feel like it would be a lot more ergonomic to add a method called `into_future` which would then return something …
=> Relax atomic orderings + fix parking/unparking UB

src/lib.rs, tests/sync.rs
Most importantly this fixes the `Future` implementation on `Sender`. 
This PR removes the last usage of `SeqCst` ordering and replaces it with appropriate weaker orderings.
=> Fix and improve the Future impl on Sender

Cargo.toml, src/lib.rs, tests/helpers/mod.rs, tests/helpers/waker.rs, tests/loom.rs, tests/sync.rs
Just after publishing 0.1.4 I realized that the `try_recv` method did not properly handle being in the `UNPARKING` state. I wrote a loom based test proving this was the case, then I fixed the issue. I added a bunch of more loom tests while at it. Verifying that a lot of other poll interactions act sanely.
Ping @Cassy343. What do you think? There are too many combinations on how one can call this library right now. To be fully correct we should also have tests trying to call `recv`, `recv_timeout` etc after polling also. But that's going to explode in number of tests. This will be mitigated with `0.2` where these call combinations are no longer possible.
=> Fix try_recv (And add a bunch of loom based tests)

src/lib.rs, tests/raw.rs
=> Adding into_raw() and from_raw() methods

src/lib.rs, src/loombox.rs
Basically use `Box::leak` instead of `Box::into_raw`, resulting in a `&mut T` instead of `*mut T`, statically guaranteeing nonnull-ness.
This does not affect the MSRV (`1.60` at the time of writing)
Also removes an import that `clippy` is complaining about. (Unused on all feature combinations)
=> Remove unnecessary use of unsafe

Cargo.lock, Cargo.toml
We were lagging a bit behind here. I have not studied the changelog extensively. I'm not aware of anything specific we need. But since we were two breaking releases behind it's probably something useful/bugfixes.
=> Upgrade loom to latest

src/lib.rs, tests/sync.rs
This adds a `is_closed` method to the oneshot Sender.
The naming was copied from tokio's oneshot.
This PR was motivated by the following need.
A thread pool executor queues `FnOnce()->T` on a thread pool.
The method used to schedule the execution of such a function returns a Receiver.
When the execution of a function arrives, `is_closed` makes it possible on the executor side to detect that no one is actually waiting on the result anymore, and the executor can skip the execution of the function entirely.
=> Added is_closed method

Cargo.toml, src/lib.rs, tests/async.rs, tests/future.rs, tests/loom.rs, tests/raw.rs, tests/sync.rs
Closes #34 
Enables the `unexpected_cfgs` lint as described in https://github.com/faern/oneshot/issues/34#issuecomment-2124659776
=> re-enable "unexpected_cfgs" lint

.github/workflows/build-and-test.yml, CHANGELOG.md, Cargo.toml, src/lib.rs, src/loombox.rs, tests/async.rs, tests/future.rs, tests/helpers/mod.rs, tests/loom.rs, tests/raw.rs, tests/sync.rs
I have come to realize that with:
```toml
[target.'cfg(loom)'.dependencies]
loom = { version = "0.7.2", features = ["futures"] }
```
loom is pulled in as a mandatory dependency and pollutes `Cargo.lock`. This means it pollutes the dependency tree by quite a lot. This should be a small and lightweight library, so that's not ideal. Downstream users of this library should not need to have the entire `loom` dependency tree in their supply chain, they will/should never use it!
This PR explores making loom a proper optional dependency instead.
=> Make loom optional

.github/workflows/build-and-test.yml, src/errors.rs, src/lib.rs
* Build the crate with `--locked` to catch if `Cargo.lock` is outdated
* Build documentation to catch if it has broken links and other warnings (spoiler: it did)
* Add back `LOOM_MAX_BRANCHES=100000` since tests are flaky (apparently they still fail from time to time, but going to ignore that for now)
=> Improve CI (--locked and documentation)

.github/workflows/build-and-test.yml, CHANGELOG.md, Cargo.toml, src/lib.rs, tests/async.rs, tests/future.rs, tests/helpers/mod.rs, tests/loom.rs, tests/raw.rs, tests/sync.rs
Followup to #43. Loom is still optional, taking it out of the dependency graph and not polluting `Cargo.lock` for downstream users. But also "hide" the feature a bit more. It's still exposed in `cargo metadata` sadly. And building with `cargo build --all-features` will enable the `loom` feature. However just enabling the feature does nothing.
This puts the dependency *also* behind `[target.'cfg(oneshot_loom)'.dependencies]` and all the code that is conditional on relying on `loom` vs `std` now use `cfg(oneshot_loom)` instead of `cfg(feature = "loom")`. This (again) makes it way harder for downstream users to accidentally compile `oneshot` with loom integration turned on.
So we are back to how things were before #43 but with the following differences:
* Due to being `optional`, loom is …
=> Put loom behind cfg(oneshot_loom) again

Cargo.toml, benches/benches.rs
Criterion is a pretty big dependency, and it has a higher MSRV than the library itself and the other testing dependencies. To to be able to run `cargo test` without pulling criterion in, I had to do this hack. It's similar to the `loom` hack.
The major downside is that to run benchmarks one now has to run them with `RUSTFLAGS="--cfg criterion" cargo bench`
=> Make criterion a benchmarking only dependency

src/lib.rs
At first I just updated the sizes to match stable Rust 1.84. But I then realized the size of `Thread` was smaller again on nightly. So let's ignore the test for now and see what the standard library settles on, if anything stable at all. The standard library give no size guarantees about the struct we are testing the size of, so this test is inherently unstable! The problem lies in this library, not in `std`. I just want to have this test in place to catch library bugs that cause the `ReceiverWaker` to blow up in size unintentionally.
The Rust PR that reverted the size increase of `std::thread::Thread`, and made it go back to pre Rust 1.84 sizes is this one: https://github.com/rust-lang/rust/pull/132654
=> Ignore receiver_waker_size test since it's unstable

CHANGELOG.md, src/lib.rs
Fixes #46 and partially #26.
I avoided this initially since the type is supposed to be single producer. I myself did not run into any use case where I needed the sender to be sync. But #46 has a good argument for it: Storing the sender in an overly conservative container that requires `Sync` on its content.
No, the `Receiver` can definitely not be `Sync`. See this explanation: https://github.com/faern/oneshot/issues/26#issuecomment-1627681774
=> Implement `Sync` for `Sender`

CHANGELOG.md, src/lib.rs, tests/sync.rs
Allows polling the receiver for the channel state, without changing it or without pulling any message out.
Does this allow using `oneshot` in the way you needed it @szostid ? Sure, if your code needs to know both whether or not the channel is disconnected and if there is a message, this solution requires two method calls (and two atomic loads) instead of one. But is that a real world use case? I imagine for the majority of places where you need to check the state you are either interested in knowing if there is a message to be read, or if the sender gave up and aborted.
I could also consider going more towards your suggested route in #52. But only if we slim down the state enum to just expose `Empty`, `Message`, and `Disconnected`. The three states that any receiver code could reasonably …
=> Add `is_closed` and `has_message` to the Receiver

Cargo.toml, src/lib.rs
Shows what feature must be enabled for each method to be available.
This was split out from #57. Since this part alone is not API breaking.
=> Add feature indicators to docs.rs documentation

CHANGELOG.md, src/lib.rs
I am observing that the `unreachable!()` branch is occasionally hit in `Receiver::drop()` under multithreaded load in async scenarios. This appears to be because the `UNPARKING` state is not handled in the `match`. Now it is.
I am not 100% confident in the correctness of the logic I added here - while the code in this crate is very well commented and proved easy to work with, I do not quite have the right state transitions mapped out in my head. Therefore, I just tried to follow what a similar block in a recv implementation above does. It eliminated this crash for me, at least, but perhaps I missed something. I am not even 100% convinced whether/when the `UNPARKING` state can be reached here (I cannot rule out a programming error in my code using `oneshot` wrongly).
=> Handle UNPARKING state in Receiver::drop()
